# Default values for air-capture--simple-instagram-capture.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/airstrip-proj/air-capture/simple-instagram-capture
  tag: latest-prod
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "air-capture--simple-instagram-capture"
fullnameOverride: "air-capture--simple-instagram-capture"

service:
  type: None

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
    # cpu: 100m
    # memory: 128Mi
  # requests:
    # cpu: 100m
    # memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
